### ISSUE TITLE
Local URLs lead to 404s due to absolute pathing

### ISSUE THREAD

**Issue by hhhapz** [woojiahao/git-guide#46]
The git book is hosted at https://woojiahao.com/git-guide which causes absolute URLs (i.e all of the local URLs within the site) to resolve to 404s.

The paths in the sidebar should probably be updated to be relative (like `href="01-setup"`), or include the full base URL to always resolve correctly (like `href="https://woojiahao.com/git-guide/01-setup"`).

**Comment by woojiahao** [comment]
Fixed it by adding a sub-domain for this. I lost it when migrating from Google Domains to Porkbun, thank you for raising this @hhhapz !
